name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "deploy key: ${{ secrets.DEPLOY_KEY }}"